#!/bin/bash

#
# Script to build shiftfs inside the flatcar dev container
#
# Note: the shiftfs sources are pulled from https://github.com/nestybox/shiftfs-dkms.
# (which is a git clone of https://github.com/toby63/shiftfs-dkms.git shiftfs-k510).
#

result_dir=$1
if [ -z "$result_dir" ]; then
	printf "Usage: $0 <result-dir> <target-kernel>\n"
	exit 1
fi

target_kernel=$2
if [ -z "$target_kernel" ]; then
	printf "Usage: $0 <result-dir> <target-kernel>\n"
	exit 1
fi

distro=$(grep "^ID=" /etc/os-release | cut -d "=" -f2)

if [[ $distro != "flatcar" ]]; then
	printf "Must run inside flatcar dev container (detected distro = $distro).\n"
	exit 1
fi

artifact=${result_dir}/shiftfs.ko

if [ -f ${artifact} ]; then
	printf "${artifact} already exists; skipping build.\n"
	exit 0
fi

# TODO: automatically choose the appropriate version of the shiftfs-dkms based on the flatcar kernel
pushd .
cd /root
git clone -b k5.10 https://github.com/toby63/shiftfs-dkms.git
chmod 777 shiftfs-dkms
cd shiftfs-dkms
sudo -u rootless ./update1

# These trick the build scripts to think it's running on a flatcar kernel
# (rather than the kernel of the machine where the build occurs)
sed -i "s@^KVERSION :=.*@KVERSION := $target_kernel@g" Makefile
sed -i "s@^KDIR.*@KDIR ?= /lib/modules/$target_kernel/build@g" Makefile

ln -s /lib/modules/${target_kernel} /lib/modules/$(uname -r)
echo "Created symlink from /lib/modules/$(uname -r) -> /lib/modules/${target_kernel}"

# Build the shiftfs module
make -f Makefile.dkms

# Decompress
popd
xz -d /lib/modules/${target_kernel}/kernel/fs/shiftfs.ko.xz

# Copy resulting artifact
mkdir -p ${result_dir}
cp /lib/modules/${target_kernel}/kernel/fs/shiftfs.ko ${artifact}

# Cleanup build dir
rm -rf /root/shiftfs-dkms

printf "\nshiftfs build complete (result in ${artifact}).\n"
